// Mocks generated by Mockito 5.4.6 from annotations
// in product_catalog_test/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:product_catalog_test/features/startup/data/datasources/local_product_datasource.dart'
    as _i9;
import 'package:product_catalog_test/features/startup/domain/repositories/startup_repository.dart'
    as _i10;
import 'package:product_catalog_test/shared/data/datasources/product_datasource.dart'
    as _i6;
import 'package:product_catalog_test/shared/data/datasources/product_hive_datasource.dart'
    as _i7;
import 'package:product_catalog_test/shared/domain/entities/product_entity.dart'
    as _i4;
import 'package:product_catalog_test/shared/domain/enums/simulation_mode.dart'
    as _i8;
import 'package:product_catalog_test/shared/domain/models/filter_query.dart'
    as _i5;
import 'package:product_catalog_test/shared/domain/repositories/product_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductEntity>> fetchProducts({
    _i5.FilterQuery? filter,
    int? offset = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #filter: filter,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.ProductEntity>>.value(
              <_i4.ProductEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<_i4.ProductEntity?> fetchProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [id]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);

  @override
  _i3.Future<_i4.ProductEntity?> updateProduct(_i4.ProductEntity? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);
}

/// A class which mocks [ProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDataSource extends _i1.Mock implements _i6.ProductDataSource {
  MockProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductEntity>> fetchProducts({
    _i5.FilterQuery? filter,
    int? offset = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #filter: filter,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.ProductEntity>>.value(
              <_i4.ProductEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<_i4.ProductEntity?> fetchProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [id]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);

  @override
  _i3.Future<_i4.ProductEntity?> updateProduct(_i4.ProductEntity? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);
}

/// A class which mocks [ProductHiveDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductHiveDataSource extends _i1.Mock
    implements _i7.ProductHiveDataSource {
  MockProductHiveDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SimulationMode get simulationMode =>
      (super.noSuchMethod(
            Invocation.getter(#simulationMode),
            returnValue: _i8.SimulationMode.success,
          )
          as _i8.SimulationMode);

  @override
  set simulationMode(_i8.SimulationMode? _simulationMode) => super.noSuchMethod(
    Invocation.setter(#simulationMode, _simulationMode),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> cacheProducts(List<_i4.ProductEntity>? products) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProducts, [products]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.ProductEntity>> getCachedProducts({
    _i5.FilterQuery? filter,
    int? offset = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProducts, [], {
              #filter: filter,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.ProductEntity>>.value(
              <_i4.ProductEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<_i4.ProductEntity?> getCachedProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProductById, [id]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.ProductEntity>> fetchProducts({
    _i5.FilterQuery? filter,
    int? offset = 0,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #filter: filter,
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.ProductEntity>>.value(
              <_i4.ProductEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductEntity>>);

  @override
  _i3.Future<_i4.ProductEntity?> fetchProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [id]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);

  @override
  _i3.Future<_i4.ProductEntity?> updateProduct(_i4.ProductEntity? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<_i4.ProductEntity?>.value(),
          )
          as _i3.Future<_i4.ProductEntity?>);
}

/// A class which mocks [LocalProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalProductDataSource extends _i1.Mock
    implements _i9.LocalProductDataSource {
  MockLocalProductDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductEntity>> loadProducts() =>
      (super.noSuchMethod(
            Invocation.method(#loadProducts, []),
            returnValue: _i3.Future<List<_i4.ProductEntity>>.value(
              <_i4.ProductEntity>[],
            ),
          )
          as _i3.Future<List<_i4.ProductEntity>>);
}

/// A class which mocks [StartupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartupRepository extends _i1.Mock implements _i10.StartupRepository {
  MockStartupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initializeData() =>
      (super.noSuchMethod(
            Invocation.method(#initializeData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
